### ISSUE TITLE
Wrong left and right margins of the view with layout-card

### ISSUE THREAD

**Issue by bieniu** [thomasloven/lovelace-layout-card#64] opened 2020-04-01 09:14 UTC
With `layout-card` left and right margins of the view are different than without the card. Could it be fixed?

Without `layout-card`:

![image](https://user-images.githubusercontent.com/478555/78119554-e80dcb80-7408-11ea-9af1-9678b3db13d0.png)

With `layout-card`:

![image](https://user-images.githubusercontent.com/478555/78119582-f2c86080-7408-11ea-9e82-cf64c784c5a2.png)

My configuration:
```yaml
- id: climate
    icon: mdi:cloud
    title: "Klimat"
    path: climate
    panel: true
    cards:
      - type: custom:layout-card
        max_columns: 5
        cards:
          - type: custom:bom-weather-card
            ...
            ...
```

**Comment by thomasloven** [comment] 2020-06-26 21:00
Should be fixed in release 14.

**Closed by thomasloven** 2020-06-26 21:00 UTC

**Comment by daniele-athome** [comment] 2021-01-21 20:22
Sorry for bumping a closed thread, but I think somehow it's related.
I'm having the same problem in #93 (as in causing horizontal scroll on mobile), but caused by this change: https://github.com/thomasloven/lovelace-layout-card/commit/bc1d8f305079f28cdf7c4f1919969ebffecde5b0#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R214-R219

Commenting out the margin rules fixes the problem. I'm using a vertical columns layout. Any chance you remember why you introduced those margins?

Thanks!
