### ISSUE TITLE
switching of views shows only one column of cards

### ISSUE THREAD

**Issue by deluxestyle** [thomasloven/lovelace-layout-card#45] opened 2020-01-05 10:05 UTC
hass.io: 0.103.5
lovelace-layout-card: 7

If I switch between views then it happens very often that only one column of cards will be shown. 
On every browser, chrome, firefox, safari on ios
I've cleared the cache but nothing changed

How it should be
![image](https://user-images.githubusercontent.com/662779/71778224-30a11e80-2fab-11ea-9da5-a4141a074a60.png)

How it is very often
![image](https://user-images.githubusercontent.com/662779/71778228-3e56a400-2fab-11ea-85d0-ba641e1a6f97.png)

**Comment by aegjoyce** [comment] 2020-01-05 17:15
I've got the same issue since the latest update too. Can confirm reverting to version 6 fixes the problem.

**Comment by sanderjonkers** [comment] 2020-01-06 07:24
I have the same issue of having only a single collumn after switching views. After a full browser refresh it shows the normal 3 collumns I have configured. I had this issue in version 6, and I have just updated to version 7, and the issue is still present.

I have this issue almost constantly on my wall mounted android tablet running lovelace in the Fully Kiosk browser, but I also have it sometimes using Firefox on a windows 10 laptop.

I have set the rebuild parameter to 1000, but I'm not sure if this would still function, as I can't find this parameter anymore in the readme.

I do use other custom cards within the layout cards BTW, like custom button card, mini-graph and mod-card.

This looks like the same issue as #17

**Comment by tomeeka** [comment] 2020-01-06 08:37
I have this problem too, If I put the layout-card "behind" a state-switch card, it happens all the time. (even with previous version)

**Comment by bruxy70** [comment] 2020-01-07 06:14
Same issue here.

**Comment by zeular** [comment] 2020-01-07 08:15
Mee to, I rolled back to v6 and it works.

**Comment by thomasloven** [comment] 2020-01-07 22:30
Should be fixed now.

**Closed by thomasloven** 2020-01-07 22:30 UTC
