### ISSUE TITLE
Lovelace dashboard doesn't show up until it is edited after Home Assistant upgrade

### ISSUE THREAD

**Issue by greyivy** [thomasloven/lovelace-layout-card#96] opened 2020-10-11 20:31 UTC
When lovelace is initially loaded, it's blank. If I look in the DOM, I can find `Custom element doesn't exist: layout-card`. If I go to the menu and click "Edit Dashboard", everything works normally.

This only seems to be happening on certain pages.

**Comment by chriss158** [comment] 2020-10-13 08:57
I have exactly the same problem since update to HA 0.116. 

I can reproduce the issue with this simple layout in panel mode:

```
cards:
  - entity: weather.home
    theme: Animated Weather Card
    type: weather-forecast
type: 'custom:layout-card'

```

I've cleared all cache data.

**Comment by aleksandrov1995** [comment] 2020-10-15 06:03
I have the exact same issue since upgrading to 0.116

**Comment by antoineguilbert** [comment] 2020-10-15 06:05
Same problem here

**Comment by leva3000** [comment] 2020-10-15 09:33
Same for me

**Comment by jcoin** [comment] 2020-10-17 00:30
Same problem with my dashboard

**Comment by uPagge** [comment] 2020-10-17 11:47
Same for me

**Comment by jmjmenezes** [comment] 2020-10-18 14:35
Same for me

**Comment by chriss158** [comment] 2020-10-19 18:26
Just discovered following: If the layout-card is not on the first view, everything is fine. So it seems it's related with initial loading of HA.

**Comment by noxhirsch** [comment] 2020-10-20 15:54
It seems to help to put the layout-card in a horizontal-stack or decluttering-card. Vertical-stack also works but created a padding above the layout card in my case.

**Comment by chriss158** [comment] 2020-10-20 17:11
Thanks @noxhirsch. This workaround does also work for me 👍

**Comment by uPagge** [comment] 2020-10-20 18:11
And there are developers here or no one cares

**Comment by gdoerr** [comment] 2020-10-20 18:32
I did a little testing and do not believe this is an issue with this card but a general Home Assistant issue with custom cards.

I was able to replicate the behavior with several different custom cards as well as with a very simple test card built from the Home Assistant documentation. The issue is probably related to the lazy loading changes made in HA 0.116

**Comment by noxhirsch** [comment] 2020-10-25 09:24
It seems to be fixed in HA 0.117.0 beta. I've moved the layout-card out of the horizontal-stack yesterday and haven't had a loading problem since.

**Comment by Whytey** [comment] 2020-10-25 14:18
Seeing this too - perhaps this was the lovelace defect https://github.com/home-assistant/frontend/issues/7384

**Comment by mafelipe16** [comment] 2020-11-07 19:01
Same issue here, moving to horizontal does not work, Im using Panel Mode in the view. version installed 0.117.5. Great hint reloading another view and moving back to the one with the issue.

**Comment by chriss158** [comment] 2020-11-10 14:39
For me this is fixed since 0.117.

**Comment by uPagge** [comment] 2020-11-10 15:15
> For me this is fixed since 0.117.

No, nothing has been fixed, refresh the page in the custom tab and it will disappear
since 0.117.5

**Comment by Whytey** [comment] 2020-11-10 20:58
Concur, still here in 117.5 for me also :(

**Comment by f00dagi** [comment] 2020-11-11 19:12
> When lovelace is initially loaded, it's blank. If I look in the DOM, I can find `Custom element doesn't exist: layout-card`. If I go to the menu and click "Edit Dashboard", everything works normally.
> 
> This only seems to be happening on certain pages.



> When lovelace is initially loaded, it's blank. If I look in the DOM, I can find `Custom element doesn't exist: layout-card`. If I go to the menu and click "Edit Dashboard", everything works normally.
> 
> This only seems to be happening on certain pages.

I have the same issue of lovelace being blank when loading. When hitting the three dots and refresh it reloads perfectly. Seems like. Bug to me.

**Comment by thomasloven** [comment] 2021-03-14 14:24
Please try version 2.0.0.

**Closed** 2021-04-05 19:58 UTC
