### ISSUE TITLE
History Graph Card (history-graph) not updating when layout-card is used

### ISSUE THREAD

**Issue by radoslavsirota** [thomasloven/lovelace-layout-card#58] opened 2020-03-12 07:30 UTC
Hello, 
 originaly I thought it is an frontend issue (https://github.com/home-assistant/frontend/issues/5129) but after some testing I narrowed it down to layout-card. When I use it in my configuracion, history-graph does not update in time. All other cards (at least those I use) work well. Could you please have a look at it?

```
title: Home
views:
  - id: dashboard
    path: dashboard
    icon: 'mdi:home-assistant'
    panel: true
    title: 'Dashboard'
    badges: []
    cards:
    - type: custom:layout-card
      layout: vertical
      cards:
      - type: vertical-stack
        cards:
        - entities:
            - entity: sensor.bedroom_temperature
              name: 'Spálňa'
            - entity: sensor.kids_room_temperature
              name: 'Detská izba'
            - entity: sensor.paincave_temperature
              name: 'Pracovňa'
            - entity: sensor.dining_room_temperature
              name: 'Obývačka'
            - entity: sensor.master_bathroom_temperature
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_temperature
              name: 'Hosťovská kúpelňa'
            - entity: sensor.bedroom_humidity
              name: 'Spálňa'
            - entity: sensor.kids_room_humidity
              name: 'Detská izba'
            - entity: sensor.paincave_humidity
              name: 'Pracovňa'
            - entity: sensor.dining_room_humidity
              name: 'Obývačka'
            - entity: sensor.master_bathroom_humidity
              name: 'Kúpelňa'
            - entity: sensor.guest_bathroom_humidity
              name: 'Hosťovská kúpelňa'
          hours_to_show: 8
          refresh_interval: 30
          title: 'Teplota a vlhkosť'
          type: history-graph
```

**Comment by danielolsson100** [comment] 2020-08-11 12:59
Any update on this issue ? I am facing the same problem with vertical stack and the History Graps is not refreshing automatically but the rest of my cards seems to work

**Comment by ezaton** [comment] 2020-09-08 06:24
This happens to me as well. Layout-card is in use, and I do not want to stop using it.
The problem is that history-graphs show old state (including the hour) until you manually refresh the web page.

**Comment by KoalaBear84** [comment] 2020-09-08 06:26
Hmm, I thought this was fixed in 114, but indeed I still encounter it daily. Never up to date. Sometimes refreshing the page is not enough, but you need to close and reopen the page or the kill the whole app for it.

**Comment by thomasloven** [comment] 2021-03-14 14:26
Please try version 2.0.0.

**Closed** 2021-04-05 19:58 UTC

**Comment by pessorrusso** [comment] 2021-05-11 16:18
Just updated to latest version and still have the same issue.

When refreshing the page:  history graph is rendered (it shows "loading state history" and then renders)
If I move to a different  view (I use custom:state-switch) then history graphs of that view is not rendered (no loading state message and no renderization) until I refresh the page.

I also noticed that other cards that requires renderization also has issues. Example: a gauge card will the color/gauge properly but does not show the actual reading value text (until I refresh the browser).
