### ISSUE TITLE
Config is not an object break

### ISSUE THREAD

**Issue by anglrus** [thomasloven/lovelace-layout-card#73] opened 2020-06-04 14:44 UTC
Hello,
I have got error: Config is not an object break

My configuration:
ui... yaml:
   - title: Home           
     path: home          
     icon: mdi:home-assistant   
     type: custom:layout-card 
     layout: vertical    
     cards: 
        !include /config/lovelace/tiles/home.yaml  

Home.yaml:

    - type: entities
      title: 1
      show_header_toggle: false
      entities:
        - entity: sensor.time
          name: Текущее время
          icon: mdi:clock-outline

I tried to move block 
    type: custom:layout-card 
    layout: vertical    
    cards: 
from ui to home.yaml. The same error.

If this block have in both files break doesn't work
Thank you

**Comment by thomasloven** [comment] 2020-06-26 20:59
Duplicate of #62

**Closed by thomasloven** 2020-06-26 20:59 UTC
