### ISSUE TITLE
Card forces close on keyboard (android - chrome)

### ISSUE THREAD

**Issue by RolandGoud** [thomasloven/lovelace-layout-card#34] opened 2019-11-03 20:36 UTC
When the layout card is active, and you want to add text to a card (for example ourgroceries card) the keyboard is forced shut before you can type anything

Tested on both tabet and phone (both samsung), will test other brand tablet asap.

Works fine in the HA app and Chrome on iOS,

**Comment by Svarstad** [comment] 2019-11-06 20:49
It's because the keyboard is changing the window size of the page and the module is recreating the cards on resize of the window.

**Comment by RolandGoud** [comment] 2019-11-06 20:59
oK, so if this is the case..... Got any workarounds for it?

**Comment by Svarstad** [comment] 2019-11-07 19:45
I just made a quickfix for my installation since i don't see the use of resize on mobile device. 
In the layout-card.js -> line 18 or something: 
`   window.addEventListener('resize', () => this.build());`
Then wrap it with: 
```
    if (screen.width > 1055 ){
        window.addEventListener('resize', () => this.build());
    }
```
reason of the value 1055 is because my layout breaks down to one column at 1054px if I recall right :) hope this is helping.

**Comment by thomasloven** [comment] 2019-11-12 09:38
Hi.

Please try this with the latest version and let me know if there are still issues!

**Comment by thomasloven** [comment] 2019-11-12 09:39
> I just made a quickfix for my installation since i don't see the use of resize on mobile device.

The resize event fires when you turn your phone sideways... that's pretty useful.

**Comment by thomasloven** [comment] 2019-11-12 09:42
Also, duplicate of #25.

**Comment by dimmanramone** [comment] 2020-01-05 18:53
Any plans for a fix for this one? Or any updates? I'm using the [search card](https://github.com/postlund/search-card) with the layout card but unfortunately it is impossible to use on mobile.

**Comment by pservais** [comment] 2020-01-18 07:49
Same problem here. Any progress in fixing this?

**Comment by thomasloven** [comment] 2021-03-14 14:27
Please try version 2.0.0.

**Closed** 2021-04-05 19:57 UTC
