### ISSUE TITLE
Don't have any option to select the layout

### ISSUE THREAD

**Issue by jacotec** [thomasloven/lovelace-layout-card#175] opened 2021-12-08 19:15 UTC
My Home Assistant version: 2021.11.5

Layout-card version (FROM BROWSER CONSOLE): 2.3.1

What I am doing:

I want to activate the Layout card options.

What I expected to happen:

I expect to have see the option in the configurations

What happened instead:

I don't see any option to configure the Layout:

<img width="1128" alt="2021-12-08_20-09-09" src="https://user-images.githubusercontent.com/3321655/145269381-c2569c2a-d69d-48a9-ab5f-c683e4bf89f0.png">

<img width="685" alt="2021-12-08_20-08-37" src="https://user-images.githubusercontent.com/3321655/145269404-bcf9f38a-7ef0-4316-96e9-545c4d25251e.png">

<img width="1018" alt="2021-12-08_20-14-27" src="https://user-images.githubusercontent.com/3321655/145269758-7a58ec1e-2768-43d5-a1e8-e3c5c22e7b1d.png">

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by michapr** [comment] 2022-01-10 16:25
Same issue for me... Thanks for opening ;)

**Comment by pvillanyi** [comment] 2022-02-16 05:41
Same for me

**Comment by Daniel15** [comment] 2022-02-19 20:11
Try restart Home Assistant... I didn't see the layout-card options until I restarted.

**Comment by thomasloven** [comment] 2022-02-21 20:34
Duplicate of #167

**Closed by thomasloven** 2022-02-21 20:34 UTC
