### ISSUE TITLE
no layout tab appearing

### ISSUE THREAD

**Issue by Davecl** [thomasloven/lovelace-layout-card#124] opened 2021-03-17 12:31 UTC
I have installed the latest version, both manually and via HACS but when I go to edit dashboard and then edit view no layout tab is there.
I just get settings, badges and visibility

**Comment by thomasloven** [comment] 2021-03-17 13:04
Duplicate of #119

**Closed by thomasloven** 2021-03-17 13:04 UTC

**Comment by Davecl** [comment] 2021-03-18 05:44
I have 2021.3.4 home assistant and 2.1.1 layout card
still not getting the layout tab

**Comment by thomasloven** [comment] 2021-03-19 08:50
Then please open a new issue and include your version info and browser console output.
